{
 "title": "Cache Class Details",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(com_coremedia_Cache_Classes_Capacity{},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(com_coremedia_Cache_Classes_Capacity{app_kubernetes_io_instance=\"$instance\"}, app_kubernetes_io_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(com_coremedia_Cache_Classes_Capacity{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\"},kubernetes_pod_name)"
    }
   },
   {
    "name": "CacheClass",
    "query": {
     "query": "label_values(com_coremedia_Cache_Classes_Capacity{app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\",kubernetes_pod_name=~\"$pod\"}, CacheClass)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Utilization %",
   "type": "graph",
   "description": "Capacity for this cache class (in class specific weight) (com.coremedia<type=Cache.Classes, CacheClass=\"com.coremedia.livecontext.ecommerce.cache.MarketingSpot\", application=blueprint><>Capacity)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(com_coremedia_Cache_Classes_Capacity{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass'})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "avg(com_coremedia_Cache_Classes_Level{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass'})",
     "legendFormat": "Current"
    },
    {
     "expr": "avg(com_coremedia_Cache_Classes_Utilization{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass'})",
     "legendFormat": "Utilization % [1m]"
    }
   ]
  },
  {
   "title": "CacheOperations",
   "type": "graph",
   "description": "Evaluate, Evict, Update, Remove, Errors\nPer Second ",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(com_coremedia_Cache_Classes_Evaluated{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"}[3m])",
     "legendFormat": "Evaluated"
    },
    {
     "expr": "avg(rate(com_coremedia_Cache_Classes_Evicted{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"}[3m]))",
     "legendFormat": "Evicted"
    },
    {
     "expr": "avg(rate(com_coremedia_Cache_Classes_Updated{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"}[3m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "avg(rate(com_coremedia_Cache_EvaluationErrors{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"}[3m]))",
     "legendFormat": "EvaluationErrors"
    },
    {
     "expr": "avg(rate(com_coremedia_Cache_Classes_Removed{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"}[3m]))",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "Avg. EvaluationTime",
   "type": "graph",
   "description": "Average time spent to evaluate keys of this class, taking into account all evaluations [ms] (com.coremedia<type=Cache.Classes, CacheClass=\"com.coremedia.livecontext.ecommerce.cache.MarketingSpot\", application=blueprint><>AverageEvaluationTime)",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(com_coremedia_Cache_Classes_AverageEvaluationTime{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Average EvaluationTime"
    }
   ]
  },
  {
   "title": "Cache Statistics [1m]",
   "type": "graph",
   "description": "weight (Evictions/Insertions/Miss/Removal) per minute [1 minute Average]",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(com_coremedia_Cache_Classes_EvictionRate{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "EvictionRate [1m]"
    },
    {
     "expr": "avg(com_coremedia_Cache_Classes_InsertionRate{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "InsertionRate [1m]"
    },
    {
     "expr": "avg(com_coremedia_Cache_Classes_MissRate{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "MissRate [1m]"
    },
    {
     "expr": "avg(com_coremedia_Cache_Classes_RemovalRate{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "RemovalRate [1m]"
    }
   ]
  },
  {
   "title": "Cache Statistics [5m]",
   "type": "graph",
   "description": "weight (Evictions/Insertions/Miss/Removal) per minute [5 minute Average]",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(com_coremedia_Cache_Classes_EvictionRate5m{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "EvictionRate [5m]"
    },
    {
     "expr": "avg(com_coremedia_Cache_Classes_InsertionRate5m{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "InsertionRate [5m]"
    },
    {
     "expr": "avg(com_coremedia_Cache_Classes_MissRate5m{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "MissRate [5m]"
    },
    {
     "expr": "avg(com_coremedia_Cache_Classes_RemovalRate5m{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",CacheClass='$CacheClass',kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "RemovalRate [5m]"
    }
   ]
  },
  {
   "title": "EvaluationErrors (All Caches)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(com_coremedia_Cache_EvaluationErrors{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",kubernetes_pod_name=~\"$pod\"}[3m]))by(kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}