{
 "title": "CAP Client",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(com_coremedia_Cache_Classes_Capacity{}, kubernetes_namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(com_coremedia_CapConnection_Open{kubernetes_namespace=\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(com_coremedia_CapConnection_Open{app_kubernetes_io_instance=\"$instance\"}, app_kubernetes_io_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(com_coremedia_CapConnection_Open{app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\"},kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CapConnection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "com_coremedia_CapConnection_Open{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\"}\r",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "HeapCache Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(com_coremedia_CapConnection_HeapCacheSize{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(com_coremedia_CapConnection_HeapCacheLevel{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "ContentRepositoryHealthy",
   "type": "stat",
   "description": "Signals if the content repository is healthy. This is a value derived from ContentRepositoryRequired and ContentRepositoryAvailable (see JavaDoc for details).\n",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_coremedia_CapConnection_ContentRepositoryHealthy{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WorkflowRepositoryHealthy",
   "type": "stat",
   "description": "Signals if the workflow repository is healthy. This is a value derived from WorkflowRepositoryRequired and WorkflowRepositoryAvailable (see JavaDoc for details).",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_coremedia_CapConnection_WorkflowRepositoryHealthy{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CapListRepositoryHealthy",
   "type": "stat",
   "description": "Signals if the caplist repository is healthy. This is a value derived from CapListRepositoryRequired and CapListRepositoryAvailable (see JavaDoc\nfor details).",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_coremedia_CapConnection_CapListRepositoryHealthy{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "BlobCache Usage",
   "type": "graph",
   "description": "the number of bytes of disk space that is currently used for caching blobs",
   "gridPos": { "h": 9, "w": 18, "x": 5, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(com_coremedia_CapConnection_BlobCacheSize{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(com_coremedia_CapConnection_BlobCacheLevel{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "BlobStreamingSizeThreshold",
   "type": "stat",
   "description": "the blob size threshold for streaming, in bytes (com.coremedia<type=CapConnection, application=blueprint><>BlobStreamingSizeThreshold)",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(com_coremedia_CapConnection_BlobStreamingSizeThreshold{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\"})",
     "legendFormat": "{{kuberntes_pod_name}}"
    }
   ]
  },
  {
   "title": "MaxCachedBlobSize",
   "type": "stat",
   "description": "the maximum size of a blob to be cached on the local disk (com.coremedia<type=CapConnection, application=coremedia><>MaxCachedBlobSize)",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "com_coremedia_CapConnection_MaxCachedBlobSize{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "EventChunkSize",
   "type": "stat",
   "description": "the maximum number of primary events that are fetched in one chunk when attaching a listener to the content repository (com.coremedia<type=CapConnection, application=blueprint><>EventChunkSize)",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "com_coremedia_CapConnection_EventChunkSize{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Blob Streaming Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(com_coremedia_CapConnection_BlobStreamingThreads{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Cache Misses [3m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(rate(com_coremedia_CapConnection_HeapCacheFaults{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",kubernetes_pod_name=~\"$pod\"}[3m]))",
     "legendFormat": "HeapCache Miss"
    },
    {
     "expr": "avg(rate(com_coremedia_CapConnection_BlobCacheFaults{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\",kubernetes_pod_name=~\"$pod\"}[3m]))",
     "legendFormat": "BlobCache Miss"
    }
   ]
  },
  {
   "title": "NumberOfSUSessions",
   "type": "stat",
   "description": "the number of lightweight sessions (com.coremedia<type=CapConnection, application=blueprint><>NumberOfSUSessions)",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "com_coremedia_CapConnection_NumberOfSUSessions{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\"}\r",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Max EventRetrievalDelay",
   "type": "stat",
   "description": "the maximum time that an event retrieval call waits at the Content Server, in milliseconds (com.coremedia<type=CapConnection, application=blueprint><>EventRetrievalDelayMS)",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "com_coremedia_CapConnection_EventRetrievalDelayMS{kubernetes_namespace=\"$namespace\",app_kubernetes_io_instance=\"$instance\",app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}