{
 "title": "CMCC Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(com_coremedia_Server_RunLevelNumeric{}, kubernetes_namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{kubernetes_namespace=\"$namespace\"}, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(com_coremedia_CapConnection_Open{app_kubernetes_io_instance=\"$instance\"}, app_kubernetes_io_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ContentServer Runlevel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_coremedia_Server_RunLevelNumeric{app_kubernetes_io_instance=\"$instance\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{app_kubernetes_io_app_type}}"
    }
   ]
  },
  {
   "title": "License valid for (Soft)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_coremedia_Server_LicenseValidUntilSoft - ((time())*1000)",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Exporter Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "CMS Sequence Nr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_coremedia_Server_RepositorySequenceNumber{app_kubernetes_io_instance=\"$instance\",kubernetes_namespace=\"$namespace\",app_kubernetes_io_name=\"content-management-server\"}"
    }
   ]
  },
  {
   "title": "MLS Sequence Nr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_coremedia_Server_RepositorySequenceNumber{app_kubernetes_io_instance=\"$instance\",kubernetes_namespace=\"$namespace\",app_kubernetes_io_name=\"master-live-server\"}"
    }
   ]
  },
  {
   "title": "RLS Replication",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_coremedia_Server_RepositorySequenceNumber{app_kubernetes_io_instance=\"$instance\",kubernetes_namespace=\"$namespace\",app_kubernetes_io_name=\"master-live-server\"} - on(pod)group_right com_coremedia_Replicator_LatestCompletedSequenceNumber{app_kubernetes_io_instance=\"$instance\",kubernetes_namespace=\"$namespace\",app_kubernetes_io_app_type=\"replication-live-server\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CapConnections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(com_coremedia_CapConnection_Stable\n+ com_coremedia_CapConnection_WorkflowRepositoryHealthy\n+ com_coremedia_CapConnection_ContentRepositoryHealthy)"
    }
   ]
  },
  { "title": "JVMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "repeat": "app",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", area=\"heap\"}[30m])\n/avg_over_time(jvm_memory_bytes_max{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}[30m])",
     "legendFormat": "HeapUsage [30m]"
    },
    {
     "expr": "avg(jvm_threads_current{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", area=\"heap\"}[30m])\n/avg_over_time(jvm_memory_bytes_max{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}[30m])",
     "legendFormat": "HeapUsage [30m]"
    },
    {
     "expr": "avg(jvm_threads_current{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", area=\"heap\"}[30m])\n/avg_over_time(jvm_memory_bytes_max{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}[30m])",
     "legendFormat": "HeapUsage [30m]"
    },
    {
     "expr": "avg(jvm_threads_current{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", area=\"heap\"}[30m])\n/avg_over_time(jvm_memory_bytes_max{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}[30m])",
     "legendFormat": "HeapUsage [30m]"
    },
    {
     "expr": "avg(jvm_threads_current{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", area=\"heap\"}[30m])\n/avg_over_time(jvm_memory_bytes_max{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}[30m])",
     "legendFormat": "HeapUsage [30m]"
    },
    {
     "expr": "avg(jvm_threads_current{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", area=\"heap\"}[30m])\n/avg_over_time(jvm_memory_bytes_max{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}[30m])",
     "legendFormat": "HeapUsage [30m]"
    },
    {
     "expr": "avg(jvm_threads_current{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", area=\"heap\"}[30m])\n/avg_over_time(jvm_memory_bytes_max{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}[30m])",
     "legendFormat": "HeapUsage [30m]"
    },
    {
     "expr": "avg(jvm_threads_current{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", area=\"heap\"}[30m])\n/avg_over_time(jvm_memory_bytes_max{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}[30m])",
     "legendFormat": "HeapUsage [30m]"
    },
    {
     "expr": "avg(jvm_threads_current{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", area=\"heap\"}[30m])\n/avg_over_time(jvm_memory_bytes_max{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}[30m])",
     "legendFormat": "HeapUsage [30m]"
    },
    {
     "expr": "avg(jvm_threads_current{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", area=\"heap\"}[30m])\n/avg_over_time(jvm_memory_bytes_max{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}[30m])",
     "legendFormat": "HeapUsage [30m]"
    },
    {
     "expr": "avg(jvm_threads_current{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", area=\"heap\"}[30m])\n/avg_over_time(jvm_memory_bytes_max{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}[30m])",
     "legendFormat": "HeapUsage [30m]"
    },
    {
     "expr": "avg(jvm_threads_current{kubernetes_namespace=\"$namespace\", app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"})",
     "legendFormat": "Threads"
    }
   ]
  }
 ]
}