{
 "title": "JVM - Details",
 "description": "JVM Dashboard for Kubernetes Monitoring with Prometheus",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(com_coremedia_CapConnection_Open{},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(jvm_info{app_kubernetes_io_instance=\"$instance\"}, app_kubernetes_io_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_info{app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_info{app_kubernetes_io_instance=\"$instance\"}, kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$pod JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "label_join(jvm_info{app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", kubernetes_pod_name=~\"$pod\"}, \"jdk\", \", \", \"vendor\", \"app_kubernetes_io_nametime\", \"version\")",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", kubernetes_pod_name=~\"$pod\"}  ",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{app_kubernetes_io_instance=\"$instance\", app_kubernetes_io_name=\"$app\", kubernetes_pod_name=~\"$pod\"}*1000",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"})by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage Timeline [3m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\", image!=\"\"}[3m]))by(container)",
     "legendFormat": "{{container}} Usage"
    },
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\", image!=\"\"}[3m]))by(container)",
     "legendFormat": "{{container}} System"
    },
    {
     "expr": "avg(rate(container_cpu_user_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\", image!=\"\"}[3m]))by(container)",
     "legendFormat": "{{container}} User"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\", image!=\"\"}[3m]) )by(container)\n/ on(container,pod) \navg(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\"})by(container)",
     "legendFormat": "{{container}} Usage %"
    }
   ]
  },
  {
   "title": "Memory Usage Timeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\", image!=\"\"} ",
     "legendFormat": "{{container}} Usage"
    },
    {
     "expr": "container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\", image!=\"\"}",
     "legendFormat": "{{container}} Limit"
    }
   ]
  },
  {
   "title": "JVM Memory Area (Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{app_kubernetes_io_instance=\"$instance\", area=\"heap\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_committed{app_kubernetes_io_instance=\"$instance\", area=\"heap\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": " jvm_memory_bytes_max{app_kubernetes_io_instance=\"$instance\", area=\"heap\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{app_kubernetes_io_instance=\"$instance\", area=\"heap\",kubernetes_pod_name=~\"$pod\"}/jvm_memory_bytes_max{app_kubernetes_io_instance=\"$instance\", area=\"heap\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "JVM Memory Area (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{app_kubernetes_io_instance=\"$instance\", area=\"nonheap\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_committed{app_kubernetes_io_instance=\"$instance\", area=\"nonheap\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "java_nio_direct_MemoryUsed{app_kubernetes_io_instance=\"$instance\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "DirectByteBuffers"
    },
    {
     "expr": "java_nio_mapped_MemoryUsed{app_kubernetes_io_instance=\"$instance\", kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "MappedByteBuffers"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{app_kubernetes_io_instance=\"$instance\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JVM Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{app_kubernetes_io_instance=\"$instance\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Current"
    },
    {
     "expr": " jvm_threads_daemon{app_kubernetes_io_instance=\"$instance\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": " jvm_threads_peak{app_kubernetes_io_instance=\"$instance\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": " jvm_threads_deadlocked{app_kubernetes_io_instance=\"$instance\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Deadlocked"
    }
   ]
  },
  {
   "title": "JVM Class Loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{app_kubernetes_io_instance=\"$instance\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Loaded"
    },
    {
     "expr": " jvm_classes_loaded_total{app_kubernetes_io_instance=\"$instance\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "JVM GC Time [3m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{app_kubernetes_io_instance=\"$instance\", kubernetes_pod_name=~\"$pod\"}[3m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM GC Count Increase [3m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{app_kubernetes_io_instance=\"$instance\", kubernetes_pod_name=~\"$pod\"}[3m])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}